rename_col = {

       'count':'BuildingDensity', 
       'rich':'RichnessHighVC', 
       'prob':'PortionHighVC', 
       'cv':'VariationVC',
       'gini':'IneqVC',
       'med':'MedianVC', 
       'avg':'AvgVC', 
       'l_prob':'LocalAvgVC', 
       'net_income_ptp':'CLI', 
       'z_resid': 'Error',
       'slope_median' :'MedianSlope', 
       'slope_mean': 'MeanSlope', 
       'cmpx_rh': 'VisualRichness', 
       'cmpx_shanon':'VisualBalance', 
       'cmpx_gini':'VisualIneq',
       'snt_0':'NeutralSentiment', 
       'snt_Neg':'NegativeSentiment', 
       'snt_Pos':'PositiveSentiment', 
       'rh_snt_0':'RichnessNeutralSentiment', 
       'dist_gini':'vDistanceIneq', 
       'pano_sum':'Panorama',
       'pano_rh':'RichnessPanorama', 
       'refuge':'Refuge', 
       'Dac1':'Roof', 
       'Fas2':'Fassade',  
       'Geb12':'Building',  
       'Kue8':'ArtificialGrass',  
       'Nat3':'Nature',  
       'Veg3':'Roof', 
       'Ver6':'RoadTraffic', 
       'sky':'Sky', 
       'Abb7_1':'Industrial_1pct', 
       'Abw14_1':'WasteWaster_1pct', 
       'Flu18_1':'Airfield_1pct', 
       'Gew1_1':'WaterBody_1pct',  
       'Hel19_1':'Heliport_1pct', 
       'Keh15_1':'WasteInceneration_1pct',  
       'Lan10_1':'Agriculutre_1pct', 
       'Lan17_1':'Airport_1pct', 
       'Sak13_1':'Sacral_1pct',  
       'Sie9_1':'Settlement_1pct', 
       'Ueb5_1':'Other_1pct', 
       'Ver11_1':'HighPerformingTraffic_1pct',  
       'Was16_1':'WaterBasin_1pct',  
       'Abb7_10':'Industrial_10pct',  
       'Abw14_10':'WasteWaster_10pct', 
       'Flu18_10':'Airfield_10pct', 
       'Gew1_10':'WaterBody_10pct', 
       'Hel19_10':'Heliport_10pct', 
       'Keh15_10':'WasteInceneration_10pct',  
       'Lan10_10':'Agriculture_10pct',
       'Lan17_10':'Airport_10pct', 
       'Sak13_10':'Sacral_10pct', 
       'Sie9_10':'Settlement_10pct',
       'Ueb5_10':'Other_10pct',  
       'Ver11_10':'HighPerformingTraffic_10pct',   
       'Was16_10':'WaterBasin_10pct'

}

col_value_dscription = {

    'bldg_count':'Number of buildings in region', 
    'rich':'Number of buildings with VC greater than 100', 
    'prob':'Percentage (%) of buildings with VC greater than 100', 
    'cv':'Relative standard error of VC, measure of dispersion within the buildings in region',
    'gini':'Gini coefficient of VC, measure of inequality within the buildings in region',
    'med':'Median value of VC', 
    'avg':'Mean value of VC', 
    'l_prob':'Percentage (%) of buildings with VC greater than agglomeration average', 
    'net_income_ptp':'Average commune net-income per taxpayer', 
    'z_resid': 'Difference between Visual Capital and CLI ',
    'slope_median' :'Median terrain slope in degrees', 
    'slope_mean': 'Mean terrain slope in degrees', 
    'cmpx_rh': 'Number of visable landscape elements', 
    'cmpx_shanon':'Balance of visual share of landscape elements', 
    'cmpx_gini':'Inequality of visual share of landcape elements',
    'snt_0':'Visual share (%) of Neutral elements, as median building value', 
    'snt_Neg':'Visual share (%) of Negative landscape elements, as median building value', 
    'snt_Pos':'Visual share (%) of Positive landscape elements, as median building value', 
    'rh_snt_0':'No. Neutral landscape elements, as median building value', 
    'dist_gini':'Ineq. Distance', 
    'pano_sum':'Panorama (%)',
    'pano_rh':'No. Panoramic', 
    'refuge':'Refuge', 
    'Dac1':'Roof (%)', 
    'Fas2':'Fassade (%)',  
    'Geb12':'Building (%)',  
    'Kue8':'Artificial Grass (%)',  
    'Nat3':'Nature (%)',  
    'Veg3':'Roof (%)', 
    'Ver6':'Road (%)', 
    'sky':'Sky (%)', 
    'Abb7_1':'Industrial (1%)', 
    'Abw14_1':'Waste Waster (1%)', 
    'Flu18_1':'Airfield (1%)', 
    'Gew1_1':'WaterBody (1%)',  
    'Hel19_1':'Heliport (1%)', 
    'Keh15_1':'Waste (1%)',  
    'Lan10_1':'Agriculutre (1%))', 
    'Lan17_1':'Airport (1%)', 
    'Sak13_1':'Sacral (1%)',  
    'Sie9_1':'Settlement (1%)', 
    'Ueb5_1':'Other (1%)', 
    'Ver11_1':'High Traffic (1%)',  
    'Was16_1':'Water Basin (1%)',  
    'Abb7_10':'Industrial (1%)',  
    'Abw14_10':'Waste Waster (1%)', 
    'Flu18_10':'Airfield (10%)', 
    'Gew1_10':'WaterBody (10%)', 
    'Hel19_10':'Heliport (10%)', 
    'Keh15_10':'Waste (10%)',  
    'Lan10_10':'Agriculture (10%)',
    'Lan17_10':'Airport (10%)', 
    'Sak13_10':'Sacral (10%)', 
    'Sie9_10':'Settlement (10%)',
    'Ueb5_10':'Other (10%)',  
    'Ver11_10':'HighPerformingTraffic (10%)',   
    'Was16_10':'WaterBasin (10%)'

}