rename_col = {

       'count':'BuildingDensity', 
       'rich':'RichnessHighVC', 
       'prob':'PortionHighVC', 
       'cv':'VariationVC',
       'gini':'IneqVC',
       'med':'MedianVC', 
       'avg':'AvgVC', 
       'l_prob':'LocalAvgVC', 
       'net_income_ptp':'CLI', 
       'z_resid': 'Error',
       'slope_median' :'MedianSlope', 
       'slope_mean': 'MeanSlope', 
       'cmpx_rh': 'VisualRichness', 
       'cmpx_shanon':'VisualBalance', 
       'cmpx_gini':'VisualIneq',
       'snt_0':'NeutralSentiment', 
       'snt_Neg':'NegativeSentiment', 
       'snt_Pos':'PositiveSentiment', 
       'rh_snt_0':'RichnessNeutralSentiment', 
       'dist_gini':'vDistanceIneq', 
       'pano_sum':'Panorama',
       'pano_rh':'RichnessPanorama', 
       'refuge':'Refuge', 
       'Dac1':'Roof', 
       'Fas2':'Fassade',  
       'Geb12':'Building',  
       'Kue8':'ArtificialGrass',  
       'Nat3':'Nature',  
       'Veg3':'Roof', 
       'Ver6':'RoadTraffic', 
       'sky':'Sky', 
       'Abb7_1':'Industrial_1pct', 
       'Abw14_1':'WasteWaster_1pct', 
       'Flu18_1':'Airfield_1pct', 
       'Gew1_1':'WaterBody_1pct',  
       'Hel19_1':'Heliport_1pct', 
       'Keh15_1':'WasteInceneration_1pct',  
       'Lan10_1':'Agriculutre_1pct', 
       'Lan17_1':'Airport_1pct', 
       'Sak13_1':'Sacral_1pct',  
       'Sie9_1':'Settlement_1pct', 
       'Ueb5_1':'Other_1pct', 
       'Ver11_1':'HighPerformingTraffic_1pct',  
       'Was16_1':'WaterBasin_1pct',  
       'Abb7_10':'Industrial_10pct',  
       'Abw14_10':'WasteWaster_10pct', 
       'Flu18_10':'Airfield_10pct', 
       'Gew1_10':'WaterBody_10pct', 
       'Hel19_10':'Heliport_10pct', 
       'Keh15_10':'WasteInceneration_10pct',  
       'Lan10_10':'Agriculture_10pct',
       'Lan17_10':'Airport_10pct', 
       'Sak13_10':'Sacral_10pct', 
       'Sie9_10':'Settlement_10pct',
       'Ueb5_10':'Other_10pct',  
       'Ver11_10':'HighPerformingTraffic_10pct',   
       'Was16_10':'WaterBasin_10pct'

}